### ISSUE TITLE
Tentative Task List

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#82]
- [ ] Hotel Registration (In Admin Console)
- [ ] Login system Development in Admin End
- [ ] Hotel Admin Can create their profile
- [ ] They Can add / remove rooms 
- [ ] Can create sub sections in hotel (restraunt/bar etc)
- [ ] They Can create users and assign roles to various departments
- [ ] Invoice Generation and Management
- [ ] Login System Development in User End (in The mobile app)
- [ ] Customer Registration (Automatic Upon check in to room)
- [ ] Booking of Various Services via Customer App

**Comment by ayan-biswas0412** [comment]
can you give your thoughts on this @JanviMahajan14 @sahilit

**Comment by JanviMahajan14** [comment]
Hi @ayan-biswas0412  I think the task can be divided on the basis of various modules present in the project. I think we can start with developing the register/login page in the admin module as it will be beginner-friendly followed by CRUD functionality of ADMINS. Just wanna ask if there are some UI mockups planned by you?

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 take the lead and kindly research and start making initial issues on this and also search if we can integrate already built dashboards in it or not , for now I have no UI plans yet , you can start planning those and please start writing issues for the small tasks and link the issues here

**Comment by JanviMahajan14** [comment]
Sure ! I will work on it and create issues accordingly.
